name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3

      - run: uv sync

      - name: Type check
        run: uv tool run mypy .

      - name: Linter
        run: uv tool run ruff check

      - name: Format check
        run: uv tool run ruff format --check
